### PR TITLE
Feature/v0.11 update script

### PR DESCRIPTION
**Pull request by antmoveh**
> /kind bug
> /kind documentation

1. Added the Carina V0.11 upgrade document
2. Add Carina v0.11 Changelog
3. Modify outdated CARina documents
4. Fixed some description errors

```release-note
Update the Carina documentation
```
#110 #115

### CODE REVIEW

**Comment by antmoveh** [comment]
[](url)

**Comment by antmoveh** [comment]
1993492bf608f95052bf4ee4adefe0b

**Comment by fanhaouu** [comment]
it's better to merge these commits to one use rebase

**Comment by antmoveh** [comment]
> it's better to merge these commits to one use rebase

It's compressed into a commit

**Pull request merged**
